services:
  email-agent:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      # Persist the SQLite database
      - ./data:/app/data
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
